version: "3.7"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
